import { nunito, lora } from "../fonts/fonts";
import "./globals.css";

import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ".....",
  // openGraph: {
  //   type: "website",
  //   url: "https://yourwebsite.com",
  //   title: "Your Page Title",
  //   description: "Description for SEO",
  //   images: [
  //     {
  //       url: "/path/to/image.jpg",
  //       width: 800,
  //       height: 600,
  //       alt: "Image alt text",
  //     },
  //   ],
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="sv" className={`${lora.variable} ${nunito.variable}`}>
      <head>
        {/* Preload LCP font */}
        <link
          rel="preload"
          href="/fonts/Lora-SemiBold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <Header />
        <main id="main-content">{children}</main>
      </body>
    </html>
  );
}
